#############################################################################
# Makefile for building: libProject_JP.so
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  Project_JP.pro
# Template: app
# Command: C:\Qt_Mobile\5.9.2\android_armv7\bin\qmake.exe -o Makefile Project_JP.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\Android\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc
CXX           = C:\Android\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -D__ANDROID_API__=16 --sysroot=C:\Android\android-ndk-r15c/sysroot -isystem C:\Android\android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -isystem C:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -D__ANDROID_API__=16 --sysroot=C:\Android\android-ndk-r15c/sysroot -isystem C:\Android\android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -isystem C:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IC:\Qt_Mobile\5.9.2\android_armv7\include -IC:\Qt_Mobile\5.9.2\android_armv7\include\QtQuick -IC:\Qt_Mobile\5.9.2\android_armv7\include\QtGui -IC:\Qt_Mobile\5.9.2\android_armv7\include\QtQml -IC:\Qt_Mobile\5.9.2\android_armv7\include\QtNetwork -IC:\Qt_Mobile\5.9.2\android_armv7\include\QtCore -I. -IC:\Qt_Mobile\5.9.2\android_armv7\mkspecs\android-g++
QMAKE         = C:\Qt_Mobile\5.9.2\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt_Mobile\5.9.2\android_armv7\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt_Mobile\5.9.2\android_armv7\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = libProject_JP.so1.0.0
DISTDIR = C:\Users\Frizer\Documents\QT_Projects\Project_JP\.tmp\libProject_JP.so1.0.0
LINK          = C:\Android\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=C:\Android\android-ndk-r15c/platforms/android-16/arch-arm/ -Wl,-soname,libProject_JP.so -Wl,-rpath=C:/Qt_Mobile/5.9.2/android_armv7/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Lc:/android/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x -LC:/Qt_Mobile/5.9.2/android_armv7/lib -lQt5Quick -Lc:\utils\android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Lc:/utils/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/../lib/gcc/arm-linux-androideabi/4.9 -LC:\Qt_Mobile\5.9.2\android_armv7/lib -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lgnustl_shared -lgcc -llog -lz -lm -ldl -lc
AR            = C:\Android\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:\Android\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.obj \
		qrc_qml.obj
DIST          =   main.cpp
QMAKE_TARGET  = libProject_JP.so
DESTDIR       = 
TARGET        = libProject_JP.so


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project_JP.pro C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\android-g++\qmake.conf C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\spec_pre.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\unix.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\linux.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\sanitize.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\gcc-base.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\gcc-base-unix.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\qdevice.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\device_config.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\android-base-head.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\qconfig.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_core.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_help.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_location.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_network.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qt_functions.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qt_config.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\android-base-tail.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\android-g++\qmake.conf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\spec_post.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\exclusive_builds.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\toolchain.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\default_pre.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\resolve_config.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\default_post.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qml_debug.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\android\android.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\warn_on.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qt.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\resources.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\moc.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\unix\opengl.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\unix\thread.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qmake_use.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\file_copies.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\testcase_targets.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\exceptions.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\yacc.prf \
		C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\lex.prf \
		Project_JP.pro \
		qml.qrc \
		C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Quick.prl \
		C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Gui.prl \
		C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Qml.prl \
		C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Network.prl \
		C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Core.prl
	$(QMAKE) -o Makefile Project_JP.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\spec_pre.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\unix.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\linux.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\sanitize.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\gcc-base.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\gcc-base-unix.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\qdevice.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\device_config.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\android-base-head.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\qconfig.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_core.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gui.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_help.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_location.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_network.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qml.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quick.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sql.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_svg.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webview.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xml.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qt_functions.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qt_config.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\common\android-base-tail.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\android-g++\qmake.conf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\spec_post.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\exclusive_builds.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\toolchain.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\default_pre.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\resolve_config.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\default_post.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qml_debug.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\android\android.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\warn_on.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qt.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\resources.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\moc.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\unix\opengl.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\unix\thread.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\qmake_use.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\file_copies.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\testcase_targets.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\exceptions.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\yacc.prf:
C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\lex.prf:
Project_JP.pro:
qml.qrc:
C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Quick.prl:
C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Gui.prl:
C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Qml.prl:
C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Network.prl:
C:\Qt_Mobile\5.9.2\android_armv7\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Project_JP.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		C:\Qt_Mobile\5.9.2\android_armv7\bin\rcc.exe \
		MainLowerBannerDelegate.qml \
		Screen3SquaresDelegate.qml \
		Screen3StripesDelegate.qml \
		MainLowerBannerModel.qml \
		MainBannerModel.qml \
		Screen3.qml \
		MainWindow.qml \
		Navigator.qml \
		HeaderForm.qml \
		TabForm.qml \
		Header.qml \
		Screen.qml \
		Categories.qml \
		ButtonTab.qml \
		Screen3ViewModel.qml \
		MenuSlaider.qml \
		MainWindowForm.qml \
		main.cpp \
		main.qml \
		Screen3Form.qml \
		MainLowerBanner.qml \
		CategoriesModel.qml \
		CategoriesDelegate.qml \
		Tab.qml \
		MainBannerDelegate.qml \
		CategoriesForm.qml \
		AdsButton.qml \
		image\profileTemp.jpg \
		image\backArrowTemp.jpg \
		image\mainBanner.png \
		image\item.png \
		image\icons\hamburger.png \
		image\icons\bag.png \
		image\icons\profileSelected.png \
		image\icons\profileNotSelected.png \
		image\icons\menuSettings.png \
		image\icons\catalogSelected.png \
		image\icons\favoriteNotSelected.png \
		image\icons\homeNotSelected.png \
		image\icons\menuCatalog.png \
		image\icons\squaresNotSelected.png \
		image\icons\stripesNotSelected.png \
		image\icons\menuSearch.png \
		image\icons\delivery.png \
		image\icons\addInShoppingCart.png \
		image\icons\catalogNotSelected.png \
		image\icons\squaresSelected.png \
		image\icons\stripesSelected.png \
		image\icons\resaleNotSelected.png \
		image\icons\plus.png \
		image\icons\addedInShoppingCart.png \
		image\icons\shoppingCart.png \
		image\icons\search.png \
		image\icons\favoriteSelected.png \
		image\icons\arrow.png \
		image\icons\homeSelected.png \
		image\icons\menuSale.png \
		image\icons\menuDeals.png \
		image\icons\resaleSelected.png \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\QGuiApplication \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qguiapplication.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qtguiglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qconfig.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qlogging.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qflags.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmutex.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qtgui-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcoreapplication.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstring.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qchar.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobject.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qlist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qiterator.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qpair.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qregexp.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qeventloop.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qwindowdefs.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qinputmethod.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qlocale.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qvariant.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmap.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qdebug.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qhash.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qtextstream.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qiodevice.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qvector.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qpoint.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qset.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsharedpointer.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsize.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\QQmlApplicationEngine \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlapplicationengine.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlengine.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qurl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qurlquery.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qjsengine.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qjsvalue.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qtqmlglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qtqml-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtNetwork\qtnetworkglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtNetwork\qtnetwork-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqml.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlprivate.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlparserstatus.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlpropertyvaluesource.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmllist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmetaobject.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlerror.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmldebug.h
	C:\Qt_Mobile\5.9.2\android_armv7\bin\rcc.exe -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\data\dummy.cpp
	C:\Android\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -D__ANDROID_API__=16 --sysroot=C:\Android\android-ndk-r15c/sysroot -isystem C:\Android\android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -isystem C:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:\Android\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h C:\Qt_Mobile\5.9.2\android_armv7\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.obj: main.cpp C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\QGuiApplication \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qguiapplication.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qtguiglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qconfig.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qlogging.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qflags.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmutex.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qtgui-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcoreapplication.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstring.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qchar.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobject.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qlist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qiterator.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qpair.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qregexp.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qeventloop.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qwindowdefs.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtGui\qinputmethod.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qlocale.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qvariant.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmap.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qdebug.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qhash.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qtextstream.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qiodevice.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qvector.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qpoint.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qset.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsharedpointer.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qsize.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\QQmlApplicationEngine \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlapplicationengine.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlengine.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qurl.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qurlquery.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qjsengine.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qjsvalue.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qtqmlglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qtqml-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtNetwork\qtnetworkglobal.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtNetwork\qtnetwork-config.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqml.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlprivate.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlparserstatus.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlpropertyvaluesource.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmllist.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtCore\qmetaobject.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmlerror.h \
		C:\Qt_Mobile\5.9.2\android_armv7\include\QtQml\qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qrc_qml.obj: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.obj qrc_qml.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a exit 1
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

